### ISSUE TITLE
error string unformatted

### ISSUE THREAD

**Issue by leonstafford** [szepeviktor/phpstan-wordpress#1]
this seemed to lack the usual pretty feedback:

> Ignored error pattern /^Parameter #2 \$callable of static method WP_CLI::add_command\(\) expects callable\(\): mixed, \S+ given\.$/ was not matched in reported errors.  

https://circleci.com/gh/WP2Static/wp2static/493

https://github.com/WP2Static/wp2static/pull/398/commits/c244af202a301c1ce9b6795c249b854f0b5c07fd

https://github.com/WP2Static/wp2static/blob/c244af202a301c1ce9b6795c249b854f0b5c07fd/wp2static.php#L92

and / or 

https://github.com/WP2Static/wp2static/blob/c244af202a301c1ce9b6795c249b854f0b5c07fd/wp2static.php#L93

**Comment by szepeviktor** [comment]
This is an example for what to ignore if use WP-CLI and prove a class as a callbakc https://github.com/szepeviktor/phpstan-wordpress/blob/master/example/phpstan.neon#L29-L30

**Comment by szepeviktor** [comment]
If you don's see this phpstan error just remove it from the neon file!

**Comment by leonstafford** [comment]
Many thanks - I will read the output better next time!
