### ISSUE TITLE
Call to function is_wp_error() with int<0, max> will always evaluate to false.

### ISSUE THREAD

**Issue by Flynsarmy** [szepeviktor/phpstan-wordpress#102]
In phpstan-wordpress v1.1 (not previous versions) with PHPStan level 6, when running something along the lines of:
```php
$id = wp_insert_post([
    'post_title' => "Some Title,
]);
if (is_wp_error($id)) {
    ...
}
```
I get the errors:
> Call to function is_wp_error() with int<0, max> will always evaluate to false.
> is_wp_error(int<0, max>) will always evaluate to false.

This function can return an instance of WP_Error though [[1]](https://github.com/WordPress/wordpress-develop/blob/5.9/src/wp-includes/post.php#L4093)[[2]](https://github.com/WordPress/wordpress-develop/blob/5.9/src/wp-includes/post.php#L4142)[[3]](https://github.com/WordPress/wordpress-develop/blob/5.9/src/wp-includes/post.php#L4210)[[4]](https://github.com/WordPress/wordpress-develop/blob/5.9/src/wp-includes/post.php#L4413)[[5]](https://github.com/WordPress/wordpress-develop/blob/5.9/src/wp-includes/post.php#L4436)[[6]](https://github.com/WordPress/wordpress-develop/blob/5.9/src/wp-includes/post.php#L4567), so the code is correct.

Here's my *phpstan.neon*
```neon
includes:
    # Include this extension
    - vendor/szepeviktor/phpstan-wordpress/extension.neon
parameters:
    level: 6
    inferPrivatePropertyTypeFromConstructor: true
    paths:
        - MyFolder
```

**Comment by herndlm** [comment]
The return type extension makes it quite smart there. Are you sure that the `$wp_error` argument, which is false by default, is set to true? Without that it will never return `WP_Error`.

**Comment by Flynsarmy** [comment]
Ahh, you're absolutely right. My bad!
