### ISSUE TITLE
Add dynamic return type extension for `get_sites()`

### ISSUE THREAD

**Issue by swissspidy** [szepeviktor/phpstan-wordpress#116]
The `get_sites()` function in WordPress returns of `WP_Site[]`, `int[]` when 'fields' is set to 'ids', or `int` when 'count' is passed as a query var.

**Comment by szepeviktor** [comment]
Hello Pascal!
We need a diligent contributor! 🙃

**Comment by szepeviktor** [comment]
💡 Viktor does not let others set up multisite installations.

`if (multisite) then exit!`
