### ISSUE TITLE
Theme-related unit test errors

### ISSUE THREAD

**Issue by szepeviktor** [szepeviktor/phpstan-wordpress#120]
There are some.
https://app.travis-ci.com/github/szepeviktor/phpstan-wordpress/jobs/588038287 👀

**Comment by herndlm** [comment]
was fixed with https://github.com/szepeviktor/phpstan-wordpress/pull/122. the theme stuff was basically deactivated / not working with newer phpstan versions. maybe you want to make another patch release later to get this out too :/
