### ISSUE TITLE
How long should PHPStan take?

### ISSUE THREAD

**Issue by jdamner** [szepeviktor/phpstan-wordpress#136]
A private project I work on takes around 8-10 minutes to run analysis for. It's a bespoke theme and a bunch of bespoke/private plugins so the code base is fairly large but still seems like an excessive time period considering other tools like phpcs finish in a few seconds at most. PHPUnit takes a similar amount of time, so is this just an issue of scale?

**Comment by szepeviktor** [comment]
Hello James! 👋🏻 
Thank you for your report.

This is going on in #99

You can see which file takes longer to analyze by adding `--debug -vvv`

**Comment by herndlm** [comment]
also checkout https://gist.github.com/ruudk/41897eb59ff497b271fc9fa3c7d5fb27 maybe

**Comment by szepeviktor** [comment]
@jdamner Please follow https://github.com/phpstan/phpstan/issues/8349
