### ISSUE TITLE
phpstan does not run because it can't open wp-config.php

### ISSUE THREAD

**Issue by flip111** [szepeviktor/phpstan-wordpress#14]
From this line https://github.com/wp-plugins/schreikasten/blob/master/feed.php#L3

I get an error

```
PHP Fatal error:  require_once(): Failed opening required '../../../wp-config.php' (include_path='.:/usr/share/php') in /home/flip111/php/schreikasten/feed.php on line 3
```

Maybe this is "normal" for phpstan. But `vimeo/psalm` i can just load `vendor/php-stubs/wordpress-stubs/wordpress-stubs.php` as stubs file and the analysis runs without problems. This is likely due to a design decision of phpstan itself, but i wanted to report it here first because this package is setting up the configuration for phpstan.

**Comment by szepeviktor** [comment]
Please come with me to a bird's-eye view:

1. one does not introduce custom entry points (`feed.php`) in a WordPress plugin
1. when one does core should be loaded by require-ing `wp-load.php`, see https://github.com/wp-plugins/schreikasten/blob/master/feed.php#L3
1. files containing no definitions - e.g. `feed.php` - should not be in `autoload_files:`
1. files containing no definitions are simply analyzed, thus added to `paths:` in PHPStan config

I hope these help :)

**Comment by flip111** [comment]
I'm totally new to wordpress so i don't have the wp bird's-eye view yet :(

I found this plugin and i'm trying to give some love to it to make it more 2020.

>     1. one does not introduce custom entry points (`feed.php`) in a WordPress plugin

What does one do instead? I will try to fix it that way in the plugin.



>     2\. when one does core

What does it mean to "do core"?

>     3\. files containing no definitions

What kind of definitions? Classes only?

> I hope these help :)

Yes it helps a lot, thank you !

**Comment by szepeviktor** [comment]
> What does one do instead? I will try to fix it that way in the plugin.

Use an existing entry point https://github.com/szepeviktor/WPHW/blob/master/wp-entry-points.md

e.g. `/wp-admin/admin-post.php` - it says: "WordPress Generic Request (POST/GET) Handler"

**Comment by szepeviktor** [comment]
> What does it mean to "do core"?

it was _when one does THEN core should be loaded by require-ing wp-load.php,_

**Comment by szepeviktor** [comment]
> What kind of definitions? Classes only?

Please see https://www.php-fig.org/psr/psr-1/#23-side-effects for that.

**Comment by flip111** [comment]
> https://github.com/szepeviktor/WPHW/blob/master/wp-entry-points.md

great repository !!
