### ISSUE TITLE
Incorrect return type for `esc_sql()`, `wp_slash()` and `wp_unslash()`

### ISSUE THREAD

**Issue by IanDelMar** [szepeviktor/phpstan-wordpress#154]
`StringOrArrayDynamicFunctionReturnTypeExtension` narrows the return type to strings. While this is true for `esc_sql()`, `wp_slash()` and `wp_unslash()` do not change the type of the values. 
```php
wp_slash([true]); // gives [true]
wp_unslash(1); // gives 1
esc_sql([true]); // gives ['1']
esc_sql(1); // gives '1'
```

For `Array[]` also the return type for `esc_sql()` is incorrect.
```php
esc_sql([[1]]); // gives array<int,array<int,string>>
esc_sql([['key' => 1]]); // gives array<int,array<string,string>>
esc_sql(['key' => [1]]); // gives array<string,array<int,string>>
esc_sql(['key1' => ['key2' => 1]]); // gives array<string,array<string,string>>
// the extension gives either array<int,string> or array<string,string>
```

Currently the extension also lacks a maybe array case, ie `string|array<int|string,mixed>`, and a maybe string array key case, ie `array<int|string,mixed>`.

**Comment by IanDelMar** [comment]
Prior to WP 5.5.0 non-string values in `wp_slash()` and `wp_unslash()` were not left untouched. From v5.9.4 of [php-stubs/wordpress-stubs](https://github.com/php-stubs/wordpress-stub) `wp_slash()` and `wp_unslash()` are covered in the WP stubs.

@szepeviktor Since the return type extension takes precedence over the stubs files and given that v5.9+ accounts for 71.4% of installed versions I suggest to drop `wp_slash()` and `wp_unslash()` all together. For the majority of WP installs correct return types would be given via the stubs file. 83.1% of installs see incorrect return types, while only 16.9% of install benefit from the outdated extension. (Assuming that the distribution of installed WP versions is equal among PHPStan users and all users.) What do you think?

**Comment by szepeviktor** [comment]
I go with your decision.
https://developer.wordpress.org/reference/functions/wp_slash/
I use only the good parts of WordPress, thus no arrays into wp_slash.
