### ISSUE TITLE
Add return type for query string `$args` in `GetTermsDynamicFunctionReturnTypeExtension()`

### ISSUE THREAD

**Issue by IanDelMar** [szepeviktor/phpstan-wordpress#159]
Currently, the extension does not handle query strings in the `$args` parameter.

https://github.com/szepeviktor/phpstan-wordpress/blob/a2f369b18c55a5d2eca69d875df442dc6c9386df/src/GetTermsDynamicFunctionReturnTypeExtension.php#L65-L68

Supported functions that explicitly accept query strings:
* `get_tags()`
* `get_terms()`
* `wp_get_object_terms()`

Supported functions that implicitly accept query strings by calling `wp_parse_args()` or a function that does:
* `wp_get_post_categories()`
* `wp_get_post_tags()`
* `wp_get_post_terms()`

**Comment by szepeviktor** [comment]
> Currently, the extension does not handle query strings in the `$args` parameter.

We don't want to allow that.
@johnbillion can explain that in details.

**Comment by szepeviktor** [comment]
@IanDelMar Maybe adding a comment would help!

**Comment by szepeviktor** [comment]
`wp_function('a=apple&b=berry&c=cherry')` 🤯 

```php
wp_function([
    'a' => 'apple',
    'b' => 'berry',
    'c' => 'cherry',
])
```
✔️

**Comment by IanDelMar** [comment]
> We don't want to allow that.

In general or just for these functions?

**Comment by szepeviktor** [comment]
Would you write code like this? `wp_function('a=apple&b=berry&c=cherry')`

**Comment by IanDelMar** [comment]
No, I wouldn't but I guess there are people who do.

Should I delete it everywhere I have added it in the last few weeks?

**Comment by szepeviktor** [comment]
> Should I delete it everywhere I have added it in the last few weeks?

Yes.
For those who do we show an error. Don't we?

**Comment by IanDelMar** [comment]
I have to check. As far as I remember usually the extensions return the indetermined type if a type other than constant array is provided.

**Comment by johnbillion** [comment]
Originally I never bothered supporting query string arguments because I assumed if you're interested in strict typing then you're not going to use the string argument format. I'm not against it though.

**Comment by szepeviktor** [comment]
> if you're interested in strict typing then you're not going to use the string argument format

Users do benefit from an error that tells them to use arrays.

**Comment by IanDelMar** [comment]
@johnbillion Probably you're right.

@szepeviktor I don't mind removing the support again and let the extension return the indetermined type. I recommend to then add a comment to each affected extension that support is missing on purpose. How do you show an error? Is this done by adding a rule?

**Comment by szepeviktor** [comment]
> let the extension return the indetermined type

I'm not so brave now...

`get_terms( array|string $args = array(), ...` when `$args` is any kind of a string we should return an error: Please pass arguments as an array.

**Comment by szepeviktor** [comment]
Still I'm not able to imagine a user
- who runs PHPStan
- and writes `'a=apple&b=berry&c=cherry'`

**Comment by IanDelMar** [comment]
I'll remove the support for query string arguments next week.

**Comment by IanDelMar** [comment]
Instead of adding a rule I did this: https://github.com/php-stubs/wordpress-stubs/pull/67
