### ISSUE TITLE
autoload_files is deprecated since phpstan 0.12.26

### ISSUE THREAD

**Issue by Mte90** [szepeviktor/phpstan-wordpress#16]
Check docs https://phpstan.org/user-guide/discovering-symbols
So now is not possible to use this and maybe also phpstan-phpdoc

**Comment by szepeviktor** [comment]
> So now is not possible to use this

Have you tried latest phpstan + phpstan-wordpress?

**Comment by szepeviktor** [comment]
```
> phpstan analyze
Note: Using configuration file /home/viktor/src/toolkit4wp/phpstan.neon.dist.
⚠️  You're using a deprecated config option autoload_files. ⚠️️

You might not need it anymore - try removing it from your
configuration file and run PHPStan again.

If the analysis fails, there are now two distinct options
to choose from to replace autoload_files:
1) scanFiles - PHPStan will scan those for classes and functions
   definitions. PHPStan will not execute those files.
2) bootstrapFiles - PHPStan will execute these files to prepare
   the PHP runtime environment for the analysis.

Read more about this in PHPStan's documentation:
https://phpstan.org/user-guide/discovering-symbols

 8/8 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%


 [OK] No errors

```

**Comment by Mte90** [comment]
Yes right now :-)
If one of the config files use `autoload_files` there is an error reporting this and in CI is very uncomfortable to get that.
The new version has a better reflection system and should works better with stuff legacy like wordpress.

**Comment by szepeviktor** [comment]
Try adding `"phpstan/phpstan": "^0.12.0 <0.12.26"`
or simply `"phpstan/phpstan": "0.12.25"` to your `composer.json`

**Comment by szepeviktor** [comment]
@Mte90 here is the response from @phpstan's author https://github.com/phpstan/phpstan/issues/3410#issuecomment-640543460

**Comment by ondrejmirtes** [comment]
Using `"^<0.12.26"` is bad advice. This is the correct solution: https://github.com/szepeviktor/phpstan-wordpress/pull/17

**Comment by ondrejmirtes** [comment]
A new release version 0.6.1 was tagged with this problem fixed. Thank you.
