### ISSUE TITLE
Replace `TypeSpecifyingExtension` with `@phpstan-assert` for type narrowing

### ISSUE THREAD

**Issue by swissspidy** [szepeviktor/phpstan-wordpress#168]
Now that this package requires PHPStan 1.10.0+, It seems like `IsWpErrorFunctionTypeSpecifyingExtension`, `AssertWpErrorTypeSpecifyingExtension`, and `AssertNotWpErrorTypeSpecifyingExtension` extensions could be replaced with `@phpstan-assert` annotations, which were [introduced in PHPStan 1.9.0](https://phpstan.org/writing-php-code/narrowing-types#custom-type-checking-functions-and-methods).

These annotations would need to be added in `php-stubs/wordpress-tests-stubs` / `php-stubs/wordpress-stubs` of course.

**Comment by szepeviktor** [comment]
Latest release depends on https://github.com/szepeviktor/phpstan-wordpress/blob/v1.1.7/composer.json#L16

**Comment by herndlm** [comment]
Increase it? 🎉

**Comment by swissspidy** [comment]
PR for `is_wp_error`: https://github.com/php-stubs/wordpress-stubs/pull/69

That annotation probably doesn't work for `assertWPError` because it neither throws nor returns a bool, so we still need that extension.

But at least it means we could get rid of `IsWpErrorFunctionTypeSpecifyingExtension` at some point

**Comment by szepeviktor** [comment]
Done 🍏
