### ISSUE TITLE
`void` vs. `null`

### ISSUE THREAD

**Issue by IanDelMar** [szepeviktor/phpstan-wordpress#176]
Should we ditch `void` in the EchoKey and the EchoParameter extensions and use `null` instead? Technically there is no such thing as void in PHP. However, as of PHP 7.1.0 there is a void return type. The [PHP manual](https://www.php.net/manual/en/language.types.void.php) says
>void is a return-only type declaration indicating the function does not return a value, but the function may still terminate. Therefore, it cannot be part of a [union type](https://www.php.net/manual/en/language.types.type-system.php#language.types.type-system.composite.union) declaration. Available as of PHP 7.1.0.

It also says 
>Note: Even if a function has a return type of void it will still return a value, this value is always null.

WordPress does use `void` in union types in doc blocks... which actually should be nullable return types. See [`the_title()`](https://developer.wordpress.org/reference/functions/the_title/) for an example. Having void as return type for these functions leads to
```php
sprintf('', the_title('<span>', '</span>', false))
```
giving `Parameter #2 ...$values of function sprintf expects bool|float|int|string|null, string|void given.` though `sprintf()` is completely fine with `the_title('<span>', '</span>', false)` as it is either `string` or `null`.

I don't know why this didn't pop up earlier.

**Comment by szepeviktor** [comment]
Static analysis is about strict types.

I am sorry.
Void is different from null.
When I should return null a simple `return;` is an error.

I consider a language error PHP functions returning implicit null-s.

**Comment by szepeviktor** [comment]
Wait!

```
Return: Void if $display argument is true, current post title if $display is false.
```

Why do we have an exception in our code for `the_title`?

**Comment by szepeviktor** [comment]
I see! When [title is an empty string](https://github.com/WordPress/wordpress-develop/blob/6.2/src/wp-includes/post-template.php#L42-L56).

If that is the case one should always check whether the return value of `the_title` is a string.
I get sick 🤢 is MINUTES when talking about WordPress.

**Comment by szepeviktor** [comment]
So properly written code for WordPress is long, hard to understand ans silly.
I need to heal.

**Comment by szepeviktor** [comment]
No, this is not working.

**Comment by IanDelMar** [comment]
> No, this is not working.

You healing or the code?

**Comment by szepeviktor** [comment]
There is no solution in PHP for detecting void.
One is forced to use `/** @var string|null */`

**Comment by szepeviktor** [comment]
> You healing or the code?

Me healing.
This rabbit hole is stronger than me.
Each of these issues makes me delete all my software for WordPress from the Internet.

**Comment by IanDelMar** [comment]
Oh no! We love [szepeviktor](https://github.com/szepeviktor)/[phpstan-wordpress](https://github.com/szepeviktor/phpstan-wordpress)!

**Comment by szepeviktor** [comment]
We need a businessman who can let perfectionism go.

**Comment by herndlm** [comment]
I was also annoyed already by the fact that `wpdb::prepare` has a `string|void` return type (see also https://developer.wordpress.org/reference%2Fclasses%2Fwpdb%2Fprepare%2F/) and I can't just cast the return to string without phpstan complaining. `string|null` woudl allow that. But I think I just accepted it..

**Comment by herndlm** [comment]
but wait, as @IanDelMar quoted in the beginning
> Therefore, it cannot be part of a [union type](https://www.php.net/manual/en/language.types.type-system.php#language.types.type-system.composite.union) declaration.

and indeed it crashes spectacularly: https://3v4l.org/iRfF2

I wonder if PHPStan should be more strict with these invalid unions. Considering that PHPDoc is interpreted as it would be native type by default, the type is invalid IMO. I'll open a PHPStan issue.

**Comment by herndlm** [comment]
@johnbillion do you think we can change all those implicit null returns from `return;` to `return null;` and adapt the return types? how high is the chance to get this in WP itself? :) union types with void are invalid and looks like PHPStan is going to check this at some point too..
what would be alternative if WP is not doing this - adapt it in the stubs I suppose?

**Comment by johnbillion** [comment]
Changing a `return;` to `return null;` shouldn't have any side effects because if anything is reading the return value it'll be treated as `null`. Example: https://3v4l.org/ZXFKY .

Making those functions nullable instead of voidable sounds like a good idea.

**Comment by IanDelMar** [comment]
The return type extension for `redirect_canonical()` does override WP's incorrect usage of `void` with `null`. It seems as this has already been some issue in the past.

**Comment by IanDelMar** [comment]
Has anyone opened a ticket to get this into core? Or is planning to do so?

**Comment by herndlm** [comment]
fyi this is going to be dealt with here: https://github.com/phpstan/phpstan-src/pull/2778

all `void` returns are going to be transformed to `null` after calling a function and e.g. assigning them to a variable. that should avoid the issues some had here too. it should be fine to keep them in the phpdoc / stubs / wordpress.

**Comment by szepeviktor** [comment]
I dream about WordPress not having string|void-s
and PHP throwing fatal errors when void return values are used.

**Comment by szepeviktor** [comment]
PHPStan v 1.10.50 has this feature.

**Comment by herndlm** [comment]
> fyi this is going to be dealt with here: [phpstan/phpstan-src#2778](https://github.com/phpstan/phpstan-src/pull/2778)
> 
> all `void` returns are going to be transformed to `null` after calling a function and e.g. assigning them to a variable. that should avoid the issues some had here too. it should be fine to keep them in the phpdoc / stubs / wordpress.



> PHPStan v 1.10.50 has this feature.

I think you can close this one, no?

UPDATE: or maybe bump min PHPStan version and adapt tests if necessary?

**Comment by szepeviktor** [comment]
A bump may be necessary.
But I have no Bump Button 🔴
