### ISSUE TITLE
Add tests for conditional return types

### ISSUE THREAD

**Issue by szepeviktor** [szepeviktor/phpstan-wordpress#180]
Search for `" ? "` in https://github.com/php-stubs/wordpress-stubs/blob/master/functionMap.php

`get_post_types` tests in #177

**Comment by IanDelMar** [comment]
I think tests for `get_post_types()` as for any other function or method handled by https://github.com/php-stubs/wordpress-stubs should be part of https://github.com/php-stubs/wordpress-stubs.

**Comment by IanDelMar** [comment]
Tests are part of php-stubs/wordpress-stubs now. @szepeviktor you can close this issue.
