### ISSUE TITLE
Remove extensions substituted with conditional return types in the near future

### ISSUE THREAD

**Issue by szepeviktor** [szepeviktor/phpstan-wordpress#181]
Search for `" ? "` in https://github.com/php-stubs/wordpress-stubs/blob/master/functionMap.php

**Comment by herndlm** [comment]
This done now? 🎉

**Comment by szepeviktor** [comment]
I would say a _maybe_.

https://github.com/szepeviktor/phpstan-wordpress/blob/cdf558b76f92cc4ae66f1c629eac149857bf3e4f/composer.json#L15

What core stubs version should we require? 6.2.1?
For example 6.2.0 has no conditional return types https://github.com/php-stubs/wordpress-stubs/blob/v6.2.0/functionMap.php

**Comment by IanDelMar** [comment]
I'd go for 6.2.1.

**Comment by szepeviktor** [comment]
Done 🍏
