### ISSUE TITLE
Error: `Action callback returns Instance but should not return anything`

### ISSUE THREAD

**Issue by crstauf** [szepeviktor/phpstan-wordpress#198]
Source file (WordPress mu-plugin):
https://github.com/cssllc/mu-plugins/blob/add-phpcs-phpstan/src/cssllc-woocommerce.php

Error:

```
 ------ ----------------------------------------------------------------------------
  Line   cssllc-woocommerce.php
 ------ ----------------------------------------------------------------------------
  379    Action callback returns CSSLLC_WooCommerce but should not return anything.
 ------ ----------------------------------------------------------------------------
```

Initially reported here: https://github.com/phpstan/phpstan/discussions/9889

**Comment by johnbillion** [comment]
I think that's correct. The `instance` method is returning an instance of `CSSLLC_WooCommerce` and it's hooked into an action.

**Comment by crstauf** [comment]
Ooooh. So I need to change to a callback that will initialize the instance, and not return it. Wow. 🤦‍♂️
