### ISSUE TITLE
`wp_die()` not exclusively an early terminating function

### ISSUE THREAD

**Issue by IanDelMar** [szepeviktor/phpstan-wordpress#200]
`wp_die()` is treated as if it terminated script execution early:
https://github.com/szepeviktor/phpstan-wordpress/blob/76f783564edc0bd8f4f3a2e44f6c09a1092702d5/extension.neon#L126-L127

But for `wp_die('', '', ['exit' => false])` the script execution will not be terminated in any of WP's wp_die handlers.

```php
if (somethingIsTrue()) {
	$foo = true;
} elseif (orSomethingElseIsTrue()) {
	$foo = false;
} else {
	wp_die('', '', ['exit' => false])
}

doFoo($foo); // won't catch possibly undefined variable $foo
```

**Comment by szepeviktor** [comment]
WordPress is so weird PHPStan cannot follow.
It seems to be no `setEarlyTerminating` method in PHPStan.
https://github.com/search?q=repo%3Aphpstan%2Fphpstan-src%20earlyTerminating&type=code

What is your plan?
Never use `['exit' => false]` again? 🙃

**Comment by IanDelMar** [comment]
> What is your plan? Never use `['exit' => false]` again? 🙃

:laughing:

Don't know. Maybe putting `'wp_die' => ['($args is not non-empty-array ? never : void)'],` into the functionMap.php of WordPress stubs?

**Comment by szepeviktor** [comment]
Okay!
I am in!
Please add that and add a few tests too.

Thank you.

**Comment by szepeviktor** [comment]
Related https://github.com/php-stubs/wordpress-stubs/issues/36
