### ISSUE TITLE
`__return_null()` in `add_filter()` causes error

### ISSUE THREAD

**Issue by IanDelMar** [szepeviktor/phpstan-wordpress#221]
`__return_null()` in `add_filter()` causes a `Filter callback return statement is missing.` error. See #220. Is this intended?

Note, there is no error with the lowest supported version of PHPStan.

**Comment by szepeviktor** [comment]
I see this

https://github.com/szepeviktor/phpstan-wordpress/blob/74b9e2f572b51cab33259b3c55a88050d3cbe28b/src/HookCallbackRule.php#L211-L231

**Comment by johnbillion** [comment]
It's not intended, no.
