### ISSUE TITLE
Detect wp_die exit arg

### ISSUE THREAD

**Issue by swissspidy** [szepeviktor/phpstan-wordpress#24]
`wp_die` is listed in `earlyTerminatingFunctionCalls`, which is fine by default.

However, when passing `[ 'exit' => false ]` as the third param, it won't terminate early.

Is detection for this possible using a custom extension?

**Comment by szepeviktor** [comment]
Hello Pascal!
Yes, everything is possible.

A quote from the readme:

![kép](https://user-images.githubusercontent.com/952007/95209835-1373d780-07eb-11eb-8304-4f67c04e64bc.png)

Please never use the `exit` parameter :)

**Comment by szepeviktor** [comment]
Currently it takes 2 lines of config.

https://github.com/szepeviktor/phpstan-wordpress/blob/b931433daa21e7e757d93906283337c1be174f21/extension.neon#L39-L40

Writing a PHPStan service takes 3 000 000 lines :)

**Comment by szepeviktor** [comment]
Even disco dancing is possible :) https://youtu.be/jS0_RqBQc50?t=17

I'd like to keep this extension sustainable and not target everyone with it.
That section in the README is there for a reason.

**Comment by swissspidy** [comment]
> Please never use the exit parameter :)

Wouldn't using `wp_die` with `exit => false` _improve_ testability though?

**Comment by szepeviktor** [comment]
> Wouldn't using `wp_die` with `exit => false` _improve_ testability though?

Simply override the handler :)
https://github.com/WordPress/WordPress/blob/5f62cd1566d27be22d961c2a9af31f077efdecf7/wp-includes/functions.php#L3320-L3391

**Comment by swissspidy** [comment]
I don't need to override the handler when `_default_wp_die_handler` supports the `exit` arg 🤔 

https://github.com/WordPress/WordPress/blob/5f62cd1566d27be22d961c2a9af31f077efdecf7/wp-includes/functions.php#L3590-L3592

**Comment by szepeviktor** [comment]
> I don't need to override the handler when `_default_wp_die_handler` supports the `exit` arg 🤔

I don't have to write testable code 🤯

**Comment by szepeviktor** [comment]
I think you do understand what testable code means.

Although you may not like the restrictions that come out of it.
