### ISSUE TITLE
Function wxr_cdata not found.

### ISSUE THREAD

**Issue by carstingaxion** [szepeviktor/phpstan-wordpress#241]
Hello @szepeviktor ,

I got the following error and was wondering if [`wxr_cdata()`](https://developer.wordpress.org/reference/functions/wxr_cdata/) is not read by the stub-generator?

```sh
  :196   Function wxr_cdata not found.                                        
         🪪  function.notFound                                                
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols  
```

**Comment by szepeviktor** [comment]
Thank you for reporting this.

`wxr_cdata` is little sick function, it is defined inside another function.
https://github.com/WordPress/wordpress-develop/blob/b42f5f95417413ee6b05ef389e21b3a0d61d3370/src/wp-admin/includes/export.php#L57

Please manually add a stubs file that includes its definition.

**Comment by carstingaxion** [comment]
Ok. Thanks for your fast response!
