### ISSUE TITLE
Prepare for PHPStan 2.0

### ISSUE THREAD

**Issue by swissspidy** [szepeviktor/phpstan-wordpress#242]
* https://github.com/phpstan/phpstan/discussions/11816
* https://github.com/phpstan/phpstan-src/blob/2.0.x/changelog-2.0.md
* https://github.com/phpstan/phpstan-src/blob/2.0.x/UPGRADING.md

Notable changes:

* Requires PHP 7.4+

**Comment by szepeviktor** [comment]
> Requires PHP 7.4+

I will go for PHP 4.0 compatibility 🙃

**Comment by IanDelMar** [comment]
I am wondering whether we should leave the master branch and go for PHPStan in the 2.x branch.

**Comment by swissspidy** [comment]
Ah, was not aware of that branch. Yeah that could work.
