### ISSUE TITLE
Error when using phpstan-wordpress with PHPStan 2.0.1

### ISSUE THREAD

**Issue by thomas-price** [szepeviktor/phpstan-wordpress#260]
The following error is created when using \szepeviktor\phpstan-wordpress v1.3.5 with PHPStan 2.0.1
The update was forced to test on v2.0.1.
```
Internal error: Too few arguments to function PHPStan\Analyser\TypeSpecifier::create(), 3 passed in
     C:\...\vendor\szepeviktor\phpstan-wordpress\src\IsWpErrorFunctionTypeSpecifyingExtension.php on line 40
     and exactly 4 expected while analysing file ...
```

**Comment by IanDelMar** [comment]
v1.3.5 does not support PHPStan v2.

https://github.com/szepeviktor/phpstan-wordpress/blob/079942af95124e7e3bf95ab6ef2e006eba02e4e1/composer.json#L20

But szepeviktor/phpstan-wordpress v2 will https://github.com/szepeviktor/phpstan-wordpress/releases/tag/v2.0.0-rc.1

**Comment by szepeviktor** [comment]
@thomas-price Could you try our `2.0.0-rc.1`?

**Comment by thomas-price** [comment]
`composer update szepeviktor/phpstan-wordpress:v2.0.0-rc.1 -W`

`2.0.0-rc.1` is working well ... many thanks
and I do not need to use ` --memory-limit 2G` ... great
