### ISSUE TITLE
The v2.0.0-rc.2 package requires phpstan/phpstan: ^1.11.0

### ISSUE THREAD

**Issue by e-adrien** [szepeviktor/phpstan-wordpress#269]
Hi @szepeviktor 👋 

Thank you for this package.
I'm sorry if it's already in your mind but I noticed that the [v2.0.0-rc.2 on Packagist](https://packagist.org/packages/szepeviktor/phpstan-wordpress#v2.0.0-rc.2) requires PHPStan ^1.11.0

Have a lovely day.

**Comment by szepeviktor** [comment]
Do you mean it is a big FAILED release?

🤔 Yes it is.

**Comment by szepeviktor** [comment]
Here we go!
https://github.com/szepeviktor/phpstan-wordpress/releases/tag/v2.0.0-rc.3

Thank you Adrien!
