### ISSUE TITLE
Encourage Viktor to release 2.0.0

### ISSUE THREAD

**Issue by szepeviktor** [szepeviktor/phpstan-wordpress#270]
Please!

**Comment by LeTraceurSnork** [comment]
🙌Come on, release v2.0.0!🙌

**Comment by Karpec** [comment]
I am looking forward to it. :)

**Comment by szepeviktor** [comment]
Thank you!

new default branch: 2.x
and https://github.com/szepeviktor/phpstan-wordpress/releases/tag/v2.0.0
