### ISSUE TITLE
Do I need stubs for parent theme?

### ISSUE THREAD

**Issue by claytoncollie** [szepeviktor/phpstan-wordpress#28]
I am building a Genesis child theme and phpstan is saying it can't find certain functions that come from the parent theme. Do I need something to pull those in? I am not sure I even know the words to describe what I might need. Stubs?

```
37     Function genesis_get_nav_menu not found.                                                     
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols  
```

After reading the link mentioned above, maybe I need to include the path to the parent theme in on .neon config.

Maybe either of these applies to my situation?

https://phpstan.org/user-guide/discovering-symbols#third-party-code-outside-of-composer-dependencies

https://phpstan.org/user-guide/discovering-symbols#custom-autoloader

**Comment by szepeviktor** [comment]
Hello @claytoncollie! Of course you need to put `genesis/lib/functions/menu.php` (an others) into `scanFiles:` or [generate stubs](https://github.com/szepeviktor/phpstan-wordpress/tree/master/stub-generators) from the framework.

I see they keep the code for themselves https://my.studiopress.com/themes/genesis/

**Comment by szepeviktor** [comment]
Thank you @claytoncollie 
I've included my extension and removed your CPT-s.
