### ISSUE TITLE
Problem with polyfills for compatibility with previous WordPress versions

### ISSUE THREAD

**Issue by mundschenk-at** [szepeviktor/phpstan-wordpress#33]
As part of making my plugin Avatar Privacy PHP-8-compatible, I added a polyfill for the `is_gd_image` function introduced in WordPress 5.6.0. While my polyfill is guarded by `function_exists`, the stubs in `php-stubs/wordpress-stubs` are not, making `phpstan analyze` fail (due to Composer autoloading my functions before the stubs).

**Comment by szepeviktor** [comment]
Thank you for your report.
That is a though question.

**Comment by szepeviktor** [comment]
This is an automatically generated package.
As of today I do not see a solution for WordPress polyfills.

Two bad ones:

1. Use an older stub where that function is non-existent
2. Load WP polyfills in your code

:(

**Comment by szepeviktor** [comment]
And a number 3: `sed -i -e 's#function is_gd_image#function __is_gd_image#' vendor/php-stubs/wordpress-stubs/wordpress-stubs.php`

**Comment by szepeviktor** [comment]
Please also see https://github.com/phpstan/phpstan/issues/4407
