### ISSUE TITLE
can you add support for woocommerce function ? 

### ISSUE THREAD

**Issue by mredodos** [szepeviktor/phpstan-wordpress#39]
hi, can you add support for woocommerce function ?

**Comment by szepeviktor** [comment]
Hello! Thank you bringing this up.
Could you point out what WC function needs a PHPStan extension?
Or do you talk about [WC stubs](https://packagist.org/packages/php-stubs/woocommerce-stubs)?

**Comment by szepeviktor** [comment]
Feel free to comment!
