### ISSUE TITLE
$wpdb->last_error type should be un-narrowed after running $wpdb->query()

### ISSUE THREAD

**Issue by ZebulanStanphill** [szepeviktor/phpstan-wordpress#40]
Consider the following code:

```php
/**
 * @template T
 * @param callable(): T $callback
 * @return T
 */
function doDbTransaction(callable $callback) {
	global $wpdb;

	try {
		$wpdb->query('START TRANSACTION');
		if ($wpdb->last_error !== '') {
			throw new \Exception(
				sprintf(
					__('Starting db transaction failed. WPDB error: %s'),
					$wpdb->last_error
				)
			);
		}

		$returnValue = $callback();

		$wpdb->query('COMMIT');
		if ($wpdb->last_error !== '') {
			throw new \Exception(
				sprintf(
					__('Committing db transaction failed. WPDB error: %s'),
					$wpdb->last_error
				)
			);
		}

		return $returnValue;
	} catch (\Throwable $e) {
		$wpdb->query('ROLLBACK');
		throw $e;
	}
}
```

When using `phpstan/phpstan-strict-rules`, the second if statement causes an error to be thrown by PHPStan's analysis:

```
Strict comparison using !== between '' and '' will always evaluate to false.
```

The type was narrowed by the first if statement, but since `$wpdb->query()` can change the value of `$wpdb-last_error`, the second if statement is completely valid. The type of `$wpdb->last_error` should be un-narrowed after every `$wpdb->query()` call.

**Comment by szepeviktor** [comment]
Thank you for the report!
For very WordPressy reasons the stubs are in `bootstrapFiles:` not in `stubFiles:`.
I suspect this is the cause. PHPStan thinks `$wpdb->last_error` cannot be modified.

Could you try editing `vendor/szepeviktor/phpstan-wordpress/extension.neon` as described above and analyze this single file only?

**Comment by szepeviktor** [comment]
You can add stubs only for `wpdb` class!

```php
class wpdb {
    /**
     * The error encountered during the last query.
     *
     * @since 2.5.0
     * @var string
     */
    public $last_error;
}
```

`wp-db.stub`

**Comment by ZebulanStanphill** [comment]
I just checked: moving one or both of the entries under `bootstrapFiles` to `stubFiles` in the aforementioned `extension.neon` file doesn't get rid of the false positive.

I actually was already using my own stub file for clarifying a few types:

```php
<?php
// Normal stub just has int as return type.
/**
 * Get the current user's ID
 *
 * @since MU (3.0.0)
 *
 * @return positive-int|0 The current user's ID, or 0 if no user is logged in.
 */
function get_current_user_id() {}
```

Adding the code snippet you provided to my stub file didn't get rid of the issue either, and neither did disabling my custom stub file entirely.

**Comment by szepeviktor** [comment]
I am sorry. All you open a trac ticket and ask WordPress people to move default value from

https://github.com/WordPress/WordPress/blob/058f9903676a7efaee534a682df0a2a8b87574d8/wp-includes/wp-db.php#L80

to the constructor. :( That takes several years.

**Comment by szepeviktor** [comment]
Maybe if you remove the default value from `$last_error` in WP stubs by for example `sed` command....

**Comment by szepeviktor** [comment]
💡  These are all the side-effect of me forcing the PHPStan-WordPress marriage!

**Comment by ZebulanStanphill** [comment]
I tried removing `$last_error`'s default value from `vendor/php-stubs/wordpress-stubs/wordpress-stubs.php`, but it didn't get rid of the false positive, so I don't think the default value has anything to do with the issue. :thinking:

**Comment by szepeviktor** [comment]
Try `vendor/bin/phpstan clear-result-cache`

**Comment by szepeviktor** [comment]
> Return #Return
> 
> (int|bool) Boolean true for CREATE, ALTER, TRUNCATE and DROP queries. Number of rows affected/selected for all other queries. Boolean false on error.

https://developer.wordpress.org/reference/classes/wpdb/query/

I was sleeping!
Please check the return value of `$wpdb->query()` instead.

**Comment by ZebulanStanphill** [comment]
Thanks, that is indeed a better way to check if an error occurred. I had mistakenly thought the function would only return the number of affected rows for queries like `START TRANSACTION`, but upon further inspection of the code, I now see that isn't the case, thankfully. Technically, the type issue with `$wpdb->last_error` still exists, but I can live with that since there no longer appears to be any practical reason to check its value.

**Comment by szepeviktor** [comment]
You're welcome.
