### ISSUE TITLE
Add dynamic return type for generic functions

### ISSUE THREAD

**Issue by johnbillion** [szepeviktor/phpstan-wordpress#63]
There are several generic functions in WordPress that return a value of the same type as passed in. Here's my list so far:

* `addslashes_gpc()`
* ~~`map_deep()`~~
* `rawurlencode_deep()`
* `sanitize_category()`
* `sanitize_post()`
* `sanitize_term()`
* `stripslashes_deep()`
* `urldecode_deep()`
* `urlencode_deep()`
* `wp_slash()`
* `wp_unslash()`

We should be able to come up with a dynamic return type extension which makes the function behave like a generic and return the same type as passed in.

**Comment by szepeviktor** [comment]
```
/**
 * @template TStripslashesDeep of string|array
 * @param TStripslashesDeep $value
 * @return TStripslashesDeep
 */
function stripslashes_deep( mixed $value ) {}
```
