### ISSUE TITLE
Extend PHPStan scanning to cover `@param` tags of `apply_filters()` and `do_action()`

### ISSUE THREAD

**Issue by johnbillion** [szepeviktor/phpstan-wordpress#65]
No idea if this is possible, I'm going to look into it and maybe ask on the PHPStan discussion forums.

When PHPStan encounters a call to `apply_filters()` or `do_action()` it should validate the types of the parameters passed to it according to the `@param` tags in the preceding docblock.

Example:

```php
/**
 * Filters the date formatted based on the locale.
 *
 * @param string       $date      Formatted date string.
 * @param string       $format    Format to display the date.
 * @param int          $timestamp Unix timestamp.
 * @param DateTimeZone $timezone  Timezone.
 */
$date = apply_filters( 'wp_date', $date, $format, $timestamp, $timezone );
```

Here, PHPStan should validate that `$date`, `$format`, `$timestamp`, and `$timezone` are of the correct types and trigger an error if not. This helps to ensure that the documentation for filters and actions is accurate.

It might be possible to achieve this by treating calls to `apply_filters()` and `do_action()` in the same manner as a closure. ~~As far as PHPStan is concerned, this code produces the same result:~~

```php
/**
 * Filters the date formatted based on the locale.
 *
 * @param string       $date      Formatted date string.
 * @param string       $format    Format to display the date.
 * @param int          $timestamp Unix timestamp.
 * @param DateTimeZone $timezone  Timezone.
 */
$date = function( string $date, string $format, int $timestamp, DateTimeZone $timezone ) : string {
    return $date;
}
```

**Comment by szepeviktor** [comment]
@canvural Could you help with two sentences?

**Comment by canvural** [comment]
Hi, sounds like this can be solved by writing [stubs](https://phpstan.org/user-guide/stub-files) for `apply_filters`

**Comment by szepeviktor** [comment]
> this can be solved by

@canvural I see :) You know, in WordPress you can modify values by going through a set of filters. So `apply_filters` appears several times in WordPress. We need to typehint each of them **separately**.

**Comment by canvural** [comment]
I see. So it's complicated. I don't think this can be done just with docblocks. Maybe an extension can be written, but it's still hard because filters are registered with `add_filter` So it's dynamic.
