### ISSUE TITLE
Compatibility of WP_Nav_Menu_Item with WP_Post

### ISSUE THREAD

**Issue by IanDelMar** [szepeviktor/phpstan-wordpress#71]
PHPStan throws "Parameter # 2 $item (WP_Nav_Menu_Item) of method Class_Name::start_el() should be compatible with parameter $item (WP_Post) of method Class_Name::start_el()" when analyzing

```php
class Class_Name extends Walker_Nav_Menu {
	/**
	* Starts the element output.
	*
	* @since WP 3.0.0
	* @since WP 4.4.0 The {@see 'nav_menu_item_args'} filter was added.
	*
	* @see Walker_Nav_Menu::start_el()
	*
	* @param string           $output Used to append additional content (passed by reference).
	* @param WP_Nav_Menu_Item $item   Menu item data object.
	* @param int              $depth  Depth of menu item. Used for padding.
	* @param WP_Nav_Menu_Args $args   An object of wp_nav_menu() arguments.
	* @param int              $id     Current item ID.
	*/
	public function start_el( &$output, $item, $depth = 0, $args = null, $id = 0 ) {
		...
	}
}
```

**Comment by szepeviktor** [comment]
I think the most one can do is to ignore this specific error.

**Comment by herndlm** [comment]
We had a similar problem and ignored it too.. Wonder if an intersection type at some place could help us?
I think the last time I checked it I couldn't find a solution

**Comment by szepeviktor** [comment]
Please see this old PR https://github.com/wp-bootstrap/wp-bootstrap-navwalker/pull/453/files#diff-6f19df6a6307a48db0940e6897591fb08776d2db8a6134737aa708defdb5c92dR17-R20

**Comment by herndlm** [comment]
In user code, right. I was wondering if we can fix it here. But I guess, we can't. A post's a post and simply doesn't have those atts

**Comment by szepeviktor** [comment]
Yes.This package is a minimal effort to clean up the mess in WordPress core.
It is not my intent to fix everything including this one.
