### ISSUE TITLE
File phar://phpstan.phar/conf/bleedingEdge.neone is missing or not readable

### ISSUE THREAD

**Issue by davidshq** [szepeviktor/phpstan-wordpress#8]
I was following Tom McFarlin's directions for PHPStan found here:
https://tommcfarlin.com/better-wordpress-code-4/

This worked. But he referenced your extensions for PHPStan so I tried adding them following your directions:
https://packagist.org/packages/szepeviktor/phpstan-wordpress

Here is my composer.json file (.txt appended to get Github to allow upload):
[composer.json.txt](https://github.com/szepeviktor/phpstan-wordpress/files/3699540/composer.json.txt)

And here is my phpstan.neon.dist file (same w/txt appended)
[phpstan.neon.dist.txt](https://github.com/szepeviktor/phpstan-wordpress/files/3699538/phpstan.neon.dist.txt)

The folder structure for the plugin is:
wp-content\plugins\test\
  \src
  \vendor
  composer.json
  composer.lock
  phpstan.neon.dist
  sample-plugin.php

When I run composer update everything seems to run fine. Then I try:

`vendor/bin/phpstan analyse src`

And get back an error:

`Note: Using configuration file /var/www/phpdev.davemackey.net/wp-content/plugins/test/phpstan.neon.dist. File 'phar://phpstan.phar/conf/bleedingEdge.neon' is missing or is not readable.`

Any suggestions are appreciated. :)

**Comment by szepeviktor** [comment]
Hello @davidshq !

If you don't use the PHAR distribution of phpstan (`phpstan/phpstan-shim`) please use the commented out line https://github.com/szepeviktor/phpstan-wordpress/blob/master/example/phpstan.neon.dist#L5 - not the one beginning with `phar://`

**Comment by szepeviktor** [comment]
You should customize phpstan.neon.dist, it just a general example.

**Comment by davidshq** [comment]
Thanks, I'm just experimenting with PHPstan now, after doing as you noted above it now works correctly!

**Comment by szepeviktor** [comment]
You're welcome.
