### ISSUE TITLE
Cannot redeclare wp_set_password()

### ISSUE THREAD

**Issue by Mysak007** [szepeviktor/phpstan-wordpress#90]
Hello we have wordpress installed by composer. The composer installs it to two separate folders (wp where are all core files, wp-content etc.) And when installing something else(i.e. plugins etc.) they are installed to separate folder wp-content in root. Wordpress works good. But when trying to run phpStan there is an error
`Fatal error: Cannot redeclare wp_set_password() (previously declared in C:\wamp64\www\uw-kuppro\wp-content\vendor\roots\wp-password-bcrypt\wp-password-bcrypt.php:86) in C:\wamp64\www\uw-kuppro\wp-content\vendor\php-stubs\wordpress-s
tubs\wordpress-stubs.php on line 109004
Script wp-content/vendor/bin/phpstan analyse --debug handling the phpstan event returned with error code 255
make: *** [Makefile:2: pre-commit] Error 255
`
I presume that it is because of the folder structure? Or problem is somewhere else? On another project(only plugin for WP) your phpStan rules works great. Thanks for your help.
Michal Dolezal

**Comment by szepeviktor** [comment]
> I presume that it is because of the folder structure?

Hello Michal! 🇨🇿 
It is talked about in a pinned issue and at the end of the README.
https://github.com/szepeviktor/phpstan-wordpress/blob/master/README.md#dirty-corner-faq

You may also remove `roots/wp-password-bcrypt` just before static analysis.

**Comment by szepeviktor** [comment]
BTW You find 4 Composer configs in here https://github.com/szepeviktor/debian-server-tools/tree/master/webserver/wp-install on how I install [WordPress](https://github.com/szepeviktor/debian-server-tools/blob/master/webserver/WordPress.md).
