### ISSUE TITLE
Move dynamic return type extensions into wordpress-stubs

### ISSUE THREAD

**Issue by johnbillion** [szepeviktor/phpstan-wordpress#97]
@szepeviktor [PHPStan 1.6 added support for conditional return types in docblocks](https://phpstan.org/blog/phpstan-1-6-0-with-conditional-return-types), eg `@return ($as_float is true ? float : string)`.

Some of the dynamic return type extensions (eg. `CurrentTimeDynamicFunctionReturnTypeExtension`) could be replaced by a conditional return type doc in the `wordpress-stubs` repo instead. Then we'd only need dynamic return type extensions for functions with more complicated logic.

What do you think? Worth doing?

**Comment by johnbillion** [comment]
Example (untested):

```php
/**
 * @phpstan-return ($type is 'timestamp ? int : ($type is 'U ? int : string))
 */
function current_time( $type, $gmt = false) {}
```

**Comment by szepeviktor** [comment]
> [PHPStan 1.6 added support for conditional return types](https://phpstan.org/blog/phpstan-1-6-0-with-conditional-return-types)

I go crazy!
You have to know I'm old-fashioned guy: keep a Single type in a variable.

**Comment by szepeviktor** [comment]
As for the answer: I have no clue how to manipulate stubs in a sustainable fashion.
Keep a big `array<Class::method, $returnType>`?

**Comment by johnbillion** [comment]
I would need to check but I think [the existing functionMap file](https://github.com/php-stubs/wordpress-stubs/blob/master/functionMap.php) could be used.

Example:

```php
'current_time' => "($type is 'timestamp' ? int : ($type is 'U ? int : string))",
```

**Comment by szepeviktor** [comment]
All right.
